services:
  uptime-kuma:
    build:
      context: .
      dockerfile: docker/dockerfile
      target: release
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./data/monitors.yaml:/app/data/monitors.yaml
    ports:
      - "4001:4001"
